services:
  web-service:
    container_name: express-generic-e-commerce-service
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:8081
    env_file:
      - .prod.env
    depends_on:
      - postgres
  postgres:
    container_name: nestjs-generic-e-commerce-db
    image: postgres:16.3-alpine3.20
    restart: always
    shm_size: 128mb
    env_file:
      - .prod.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:


networks:
  default:
    name: express-generic-e-commerce-network
